### ISSUE TITLE
Compatibility with VIM 7.4

### ISSUE THREAD

**Issue by peteburn** [christianrondeau/autovim#1]
Not sure how important it is but I tried running the samples with VIM 7.4 and got the following error:

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 9 2014 17:36:41) 
Unknown option argument: "--not-a-term" 
More info with: "vim -h" 

Issue was resolved by upgrade to VIM 8.0

Running on ZorinOS (built on Lubuntu I believe)

No LSB modules are available.
Distributor ID: Zorin
Description:    Zorin 10
Release:    10
Codename:   vivid

**Comment by christianrondeau** [comment]
Hi! Thanks a lot for raising the issue; I use Vim 7.4 with Autovim successfully in Git Bash (version `version 7.4.1721`), and I _think_ it also worked with 7.4 on Termux (a linux distribution for Android), but I upgraded to 8.0 since.

What would be useful (but it's probably too late) would be to know which version of VIM you had exactly (launching `vim`, then `:version`). I believe it might be `7.4.488-3ubuntu2` based on this page: https://launchpad.net/ubuntu/vivid/+source/vim

I'll keep this issue opened and instead of verifying vim's version, I'll catch this specific error and suggest upgrading vim :)

**Comment by christianrondeau** [comment]
The `--not-a-term` parameter was added in Vim `Patch 7.4.1419`. Since I can't know vim's version without launching vim, I just catch launch errors and display a helpful message. Thanks for taking the time to create this issue!

**Comment by peteburn** [comment]
Thanks for the reply Christian. Guessed it may be out of your control. Now
that I have downloaded I am looking at this for other golf challenges and
once I have learned a bit then maybe I can help! Good to meet you on PPCG
(and I now finally have a GitHub Account :)).

**Comment by christianrondeau** [comment]
Hurrah, same here! Let me know if you need help (I might write a quick tutorial)

**Comment by christianrondeau** [comment]
Quick update on that one. I had the same problem with Travis, so I just removed `--not-a-term`. It should now even be working with 7.3! (though I test from 7.4 and up).  And I also wrote a tutorial (though it might have some errors, I didn't fully test it yet) 

https://github.com/christianrondeau/autovim/blob/master/doc/tutorial.md

**Comment by peteburn** [comment]
thanks for th update. I have started going through the "Learn Vimscript the
Hard Way" tutorial to try to get a grip on the basics but not had a lot of
time for it recently. Will hopefully be able to get a grip on it soon.

Pete
